### ISSUE TITLE
conda-env failed in a fresh miniconda install on windows

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-installer#110]
accompanies https://github.com/datalad/datalad-installer/issues/46#issuecomment-1152953317 

```shell
>>> os.system(r'"C:\Users\Yaroslav Halchenko\AppData\Local\Programs\Python\Python310\Scripts\datalad-installer" git-annex miniconda conda-env --name datalad datalad ')
2022-06-11T08:39:23-0700 [INFO    ] datalad_installer Writing environment modifications to C:\Users\YAROSL~1\AppData\Local\Temp\dl-env-dj2t5jyq.sh
2022-06-11T08:39:23-0700 [INFO    ] datalad_installer Installing git-annex via datalad/packages
2022-06-11T08:39:23-0700 [INFO    ] datalad_installer Version: None
2022-06-11T08:39:23-0700 [INFO    ] datalad_installer Downloading https://datasets.datalad.org/datalad/packages/windows/git-annex-installer_latest-snapshot_x64.exe
2022-06-11T08:39:28-0700 [INFO    ] datalad_installer Running: 'C:\Users\YAROSL~1\AppData\Local\Temp\dl-datalad-package-q83qv8w2\git-annex-installer_latest-snapshot_x64.exe' /S
2022-06-11T08:39:29-0700 [INFO    ] datalad_installer Operation requires elevation; rerunning as administrator
2022-06-11T08:39:29-0700 [INFO    ] datalad_installer Running as administrator: C:\Users\YAROSL~1\AppData\Local\Temp\dl-datalad-package-q83qv8w2\git-annex-installer_latest-snapshot_x64.exe /S
2022-06-11T08:39:33-0700 [INFO    ] datalad_installer Installing Miniconda
2022-06-11T08:39:33-0700 [INFO    ] datalad_installer Path: C:\Users\YAROSL~1\AppData\Local\Temp\dl-miniconda-wnl_jn7l
2022-06-11T08:39:33-0700 [INFO    ] datalad_installer Batch: True
2022-06-11T08:39:33-0700 [INFO    ] datalad_installer Spec: None
2022-06-11T08:39:33-0700 [INFO    ] datalad_installer Extra args: None
2022-06-11T08:39:33-0700 [INFO    ] datalad_installer Downloading and running miniconda installer
2022-06-11T08:39:33-0700 [INFO    ] datalad_installer Downloading https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe
2022-06-11T08:39:48-0700 [INFO    ] datalad_installer Installing miniconda in C:\Users\YAROSL~1\AppData\Local\Temp\dl-miniconda-wnl_jn7l
2022-06-11T08:39:48-0700 [INFO    ] datalad_installer Running: start /wait "" C:\Users\YAROSL~1\AppData\Local\Temp\tmps02jic8n\Miniconda3-latest-Windows-x86_64.exe /S /D=C:\Users\Yaroslav Halchenko\AppData\Local\Temp\dl-miniconda-wnl_jn7l
2022-06-11T08:40:23-0700 [INFO    ] datalad_installer Creating Conda environment
2022-06-11T08:40:23-0700 [INFO    ] datalad_installer Name: datalad
2022-06-11T08:40:23-0700 [INFO    ] datalad_installer Spec: None
2022-06-11T08:40:23-0700 [INFO    ] datalad_installer Extra args: None
2022-06-11T08:40:23-0700 [INFO    ] datalad_installer Running: 'C:\Users\YAROSL~1\AppData\Local\Temp\dl-miniconda-wnl_jn7l\Scripts\conda.exe' create --name datalad
Collecting package metadata (current_repodata.json): done
Solving environment: done

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.anaconda.com/pkgs/main/win-64/current_repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

If your current network has https://www.anaconda.com blocked, please file
a support request with your network engineering team.

'https://repo.anaconda.com/pkgs/main/win-64'


Traceback (most recent call last):
  File "C:\Users\Yaroslav Halchenko\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Yaroslav Halchenko\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Yaroslav Halchenko\AppData\Local\Programs\Python\Python310\Scripts\datalad-installer.exe\__main__.py", line 7, in <module>
  File "C:\Users\Yaroslav Halchenko\AppData\Local\Programs\Python\Python310\lib\site-packages\datalad_installer.py", line 2561, in main
    return manager.main(argv)
  File "C:\Users\Yaroslav Halchenko\AppData\Local\Programs\Python\Python310\lib\site-packages\datalad_installer.py", line 692, in main
    self.addcomponent(name=cr.name, **cr.kwargs)
  File "C:\Users\Yaroslav Halchenko\AppData\Local\Programs\Python\Python310\lib\site-packages\datalad_installer.py", line 741, in addcomponent
    component(self).provide(**kwargs)
  File "C:\Users\Yaroslav Halchenko\AppData\Local\Programs\Python\Python310\lib\site-packages\datalad_installer.py", line 1040, in provide
    runcmd(*cmd)
  File "C:\Users\Yaroslav Halchenko\AppData\Local\Programs\Python\Python310\lib\site-packages\datalad_installer.py", line 2420, in runcmd
    return subprocess.run(arglist, check=True, **kwargs)
  File "C:\Users\Yaroslav Halchenko\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\Users\\YAROSL~1\\AppData\\Local\\Temp\\dl-miniconda-wnl_jn7l\\Scripts\\conda.exe', 'create', '--name', 'datalad']' returned non-zero exit status 1.
```

**Comment by yarikoptic** [comment]
well. may be it was some connection issue?  I ran in conda terminal and it succeeded

**Comment by yarikoptic** [comment]
yeap. consider self-resolved.
