### ISSUE TITLE
Use shutil to move?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-installer#120]
I got

```
$> datalad-installer rclone=1.30 -m downloads.rclone.org --bin-dir /tmp/rclone-1.30
2022-07-27T17:53:21-0400 [INFO    ] datalad_installer Writing environment modifications to /home/yoh/.tmp/dl-env-_6gf1etv.sh
2022-07-27T17:53:21-0400 [INFO    ] datalad_installer Installing rclone from downloads.rclone.org
2022-07-27T17:53:21-0400 [INFO    ] datalad_installer Version: 1.30
2022-07-27T17:53:21-0400 [INFO    ] datalad_installer Bin dir: /tmp/rclone-1.30
2022-07-27T17:53:21-0400 [INFO    ] datalad_installer Man dir: None
2022-07-27T17:53:21-0400 [INFO    ] datalad_installer Downloading https://downloads.rclone.org/v1.30/rclone-v1.30-linux-amd64.zip
2022-07-27T17:53:23-0400 [INFO    ] datalad_installer Moving /home/yoh/.tmp/tmp42x2_p2s/rclone-v1.30-linux-amd64/rclone to /tmp/rclone-1.30/rclone
Traceback (most recent call last):
  File "/home/yoh/proj/datalad/datalad-maint/venvs/dev3/bin/datalad-installer", line 8, in <module>
    sys.exit(main())
  File "/home/yoh/proj/datalad/datalad-maint/venvs/dev3/lib/python3.10/site-packages/datalad_installer.py", line 2591, in main
    return manager.main(argv)
  File "/home/yoh/proj/datalad/datalad-maint/venvs/dev3/lib/python3.10/site-packages/datalad_installer.py", line 692, in main
    self.addcomponent(name=cr.name, **cr.kwargs)
  File "/home/yoh/proj/datalad/datalad-maint/venvs/dev3/lib/python3.10/site-packages/datalad_installer.py", line 741, in addcomponent
    component(self).provide(**kwargs)
  File "/home/yoh/proj/datalad/datalad-maint/venvs/dev3/lib/python3.10/site-packages/datalad_installer.py", line 1184, in provide
    bins = self.get_installer(method).install(self.NAME, **kwargs)
  File "/home/yoh/proj/datalad/datalad-maint/venvs/dev3/lib/python3.10/site-packages/datalad_installer.py", line 1312, in install
    bindir = self.install_package(package, **kwargs)
  File "/home/yoh/proj/datalad/datalad-maint/venvs/dev3/lib/python3.10/site-packages/datalad_installer.py", line 2184, in install_package
    self.manager.move_maybe_elevated(contents / binname, bin_dir / binname)
  File "/home/yoh/proj/datalad/datalad-maint/venvs/dev3/lib/python3.10/site-packages/datalad_installer.py", line 604, in move_maybe_elevated
    path.replace(dest)
  File "/usr/lib/python3.10/pathlib.py", line 1245, in replace
    self._accessor.replace(self, target)
OSError: [Errno 18] Invalid cross-device link: '/home/yoh/.tmp/tmp42x2_p2s/rclone-v1.30-linux-amd64/rclone' -> '/tmp/rclone-1.30/rclone'
```

with 0.9.0.  Detail is that I use `TMPDIR=/home/yoh/.tmp` so it is on different partition than `/tmp`

**Comment by jwodder** [comment]
@yarikoptic Unfortunately, `shutil.move()` will fail if there is already a file at the destination path.  I'm also not sure how to tell whether the source & destination paths are on the same filesystem or not; the top results I'm finding in a search involve the `st_dev` field of `os.stat()`, and I have no idea if that works on Windows.  For the record, `shutil.move()` tries to fall back to copying if any OSError occurs, but we also have to handle `PermissionErrors` by invoking `sudo`.

The best way I can think of to handle cross-filesystem moves here is to try `os.replace()`, fall back to `sudo mv` on `PermissionErrors` or to `shutil.copy2()` on other errors, with another fallback to `sudo mv` on `PermissionErrors` in the second case.  Does that sound acceptable?

**Comment by yarikoptic** [comment]
> Unfortunately, `shutil.move()` will fail if there is already a file at the destination path

`.unlink` it first if it is there if that is what is desired?  although indeed might also need falling back to calling out to `rm` etc for `sudo`.  FWIW I do not observe behavior you describe about "file at the destination path" -- seems to move just fine.

```
(git)lena:~datalad/datalad-installer[master]
$> echo 123 > /home/yoh/.tmp/tmp42x2_p2s/rclone-v1.30-linux-amd64/123
1 40590.....................................:Mon 01 Aug 2022 09:22:37 AM EDT:.
(git)lena:~datalad/datalad-installer[master]
$> ls -l /tmp/123
-rw------- 1 yoh yoh 1 Aug  1 09:22 /tmp/123
1 40591.....................................:Mon 01 Aug 2022 09:22:43 AM EDT:.
(git)lena:~datalad/datalad-installer[master]
$> python3 -c "from pathlib import Path; import shutil; shutil.move(str(Path('/home/yoh/.tmp/tmp42x2_p2s/rclone-v1.30-linux-amd64/123')), '/tmp/123')"
1 40592.....................................:Mon 01 Aug 2022 09:22:51 AM EDT:.
(git)lena:~datalad/datalad-installer[master]
$> ls -l /tmp/123
-rw------- 1 yoh yoh 4 Aug  1 09:22 /tmp/123
```

I wouldn't bother implementing "the same filesystem check".

**Comment by jwodder** [comment]
@yarikoptic To be precise: `shutil.move()` will fail *on Windows* if there is already a file at the destination path.  On \*nix, the destination will just be replaced.

I don't really like the idea of calling `unlink`.  If the user doesn't have permission to modify the containing directory, depending on the value of the `--sudo` option, they may end up prompted twice in a row about running a `sudo` command — once for `rm`, once for `mv`.

**Comment by yarikoptic** [comment]
May be then keep using replace on windows and shutil.move on posix? In any case - I trust you to make the right death decision to solve this issue
