### ISSUE TITLE
python 3.11 "support"

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-installer#133]
while trying to test datalad against 3.11 in https://github.com/datalad/datalad/pull/7199 we ran into

```
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.11.0/bin/datalad-installer", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/travis/virtualenv/python3.11.0/lib/python3.11/site-packages/datalad_installer.py", line 2640, in main
    return manager.main(argv)
           ^^^^^^^^^^^^^^^^^^
  File "/home/travis/virtualenv/python3.11.0/lib/python3.11/site-packages/datalad_installer.py", line 757, in main
    self.addcomponent(name=cr.name, **cr.kwargs)
  File "/home/travis/virtualenv/python3.11.0/lib/python3.11/site-packages/datalad_installer.py", line 796, in addcomponent
    component(self).provide(**kwargs)
  File "/home/travis/virtualenv/python3.11.0/lib/python3.11/site-packages/datalad_installer.py", line 1057, in provide
    runcmd(conda_instance.conda_exe, "install", *install_args)
  File "/home/travis/virtualenv/python3.11.0/lib/python3.11/site-packages/datalad_installer.py", line 2499, in runcmd
    return subprocess.run(arglist, check=True, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python/3.11.0/lib/python3.11/subprocess.py", line 569, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/tmp/dl-miniconda-lopaealy/bin/conda', 'install', '--yes', 'python=3.11']' returned non-zero exit status 1.
The command "eval datalad-installer --sudo ok -E new.env ${_DL_ANNEX_INSTALL_SCENARIO}" failed and exited with 1 during .
```

so it seems there is no 3.11 in main channels of conda, but I see it in conda-forge... is it worth may be adding `-c conda-forge` there?

**Comment by jwodder** [comment]
@yarikoptic So you're asking for `-c conda-forge` to be passed to the `conda install` command ... when?  If `--python-match` is supplied under Python 3.11?  How about if a `-c`/`--channel` option is added to the `miniconda` component?
