### ISSUE TITLE
support  git-annex -m datalad/packages  on OSX

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-installer#135]
tried in https://github.com/datalad/datalad/pull/7233/files due to brew failing to install on that OSX, and we have http://datasets.datalad.org/?dir=/datalad/packages/osx (now automagically updated from datalad/git-annex releases so we do not need token to download) .

But https://ci.appveyor.com/project/mih/datalad/builds/45698193/job/pbgtroljf2h292f9 showed:

```
022-12-15T17:45:35-0600 [INFO    ] datalad_installer Writing environment modifications to /Users/appveyor/DLTMP/dl-env-cy15pr6d.sh
Traceback (most recent call last):
  File "/Users/appveyor/venv3.8.15/bin/datalad-installer", line 8, in <module>
    sys.exit(main())
  File "/Users/appveyor/venv3.8.15/lib/python3.8/site-packages/datalad_installer.py", line 1788, in main
    return manager.main(argv)
  File "/Users/appveyor/venv3.8.15/lib/python3.8/site-packages/datalad_installer.py", line [65](https://ci.appveyor.com/project/mih/datalad/builds/45698193/job/pbgtroljf2h292f9#L65)7, in main
    self.addcomponent(name=cr.name, **cr.kwargs)
  File "/Users/appveyor/venv3.8.15/lib/python3.8/site-packages/datalad_installer.py", line 690, in addcomponent
    component(self).provide(**kwargs)
  File "/Users/appveyor/venv3.8.15/lib/python3.8/site-packages/datalad_installer.py", line 1032, in provide
    bins = self.get_installer(method).install(self.NAME, **kwargs)
  File "/Users/appveyor/venv3.8.15/lib/python3.8/site-packages/datalad_installer.py", line 1111, in install
    self.assert_supported_system()
  File "/Users/appveyor/venv3.8.15/lib/python3.8/site-packages/datalad_installer.py", line 1[69](https://ci.appveyor.com/project/mih/datalad/builds/45698193/job/pbgtroljf2h292f9#L69)9, in assert_supported_system
    raise MethodNotSupportedError(f"{SYSTEM} OS not supported")
datalad_installer.MethodNotSupportedError: Darwin OS not supported
Command exited with code 1
Running "on_finish" scripts
```

**Comment by jwodder** [comment]
@yarikoptic Problem: Unlike the Windows packages, the macOS packages at https://datasets.datalad.org/?dir=/datalad/packages do not include a `git-annex_latest-snapshot_x64.dmg`, which makes installing the latest version/when no version is given on the command line non-viable.  Can you add a "latest snapshot" to the macOS packages?

**Comment by yarikoptic** [comment]
I think we can/should avoid relying on `latest-snapshot` symlink there and can just use https://datasets.datalad.org/datalad/packages/windows/dist/build-version file (which AFAIK should not be windows specific) to get the most recent version and then use it for any OS -- windows, OSX or neurodebian

**Comment by jwodder** [comment]
@yarikoptic Though that link contains information valid for all platforms, the URL is only under `/windows/`.  Is that intended, and is that going to continue being the case?

**Comment by yarikoptic** [comment]
> Is that intended, and is that going to continue being the case?

ok, I have changed it and updated the http://datasets.datalad.org/datalad/packages/update.sh -- use http://datasets.datalad.org/datalad/packages/latest-version  (the windows one is still there and a symlink, IIRC it was requested by @joeyh so I will keep it there as a symlink for compatibility)
