### ISSUE TITLE
should create env file if not yet present or expanduser may be?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-installer#15]
came up in https://travis-ci.com/github/datalad/datalad/builds/215803489#L915

```
$ export _DL_ANNEX_INSTALL_SCENARIO="-E ~/.bashrc git-annex -m snapshot"
...
$ python3 datalad_installer.py -E new.env ${_DL_ANNEX_INSTALL_SCENARIO}
2021-02-02T17:27:47+0000 [INFO    ] datalad_installer Installing git-annex via snapshot
2021-02-02T17:27:47+0000 [INFO    ] datalad_installer Downloading and extracting under /tmp/dl-build-cxgy0440/git-annex.linux
2021-02-02T17:27:47+0000 [INFO    ] datalad_installer Downloading https://downloads.kitenet.net/git-annex/linux/current/git-annex-standalone-amd64.tar.gz
2021-02-02T17:27:48+0000 [INFO    ] datalad_installer Running: tar -C /tmp/dl-build-cxgy0440 -xzf /tmp/dl-build-cxgy0440/git-annex-standalone-amd64.tar.gz
Traceback (most recent call last):
  File "datalad_installer.py", line 1649, in <module>
    sys.exit(main(sys.argv))
  File "datalad_installer.py", line 1645, in main
    return manager.main(argv)
  File "datalad_installer.py", line 597, in main
    self.addcomponent(name=cr.name, **cr.kwargs)
  File "datalad_installer.py", line 633, in addcomponent
    component(self).provide(**kwargs)
  File "datalad_installer.py", line 959, in provide
    bins = self.get_installer(method).install(self.NAME, **kwargs)
  File "datalad_installer.py", line 1045, in install
    bindir = self.install_package(package, **kwargs)
  File "datalad_installer.py", line 1390, in install_package
    binpath = self._install_linux("linux/current")
  File "datalad_installer.py", line 1335, in _install_linux
    self.manager.addpath(annex_bin)
  File "datalad_installer.py", line 625, in addpath
    self.addenv(line)
  File "datalad_installer.py", line 613, in addenv
    with p.open("a") as fp:
  File "/opt/python/3.6.7/lib/python3.6/pathlib.py", line 1183, in open
    opener=self._opener)
  File "/opt/python/3.6.7/lib/python3.6/pathlib.py", line 1037, in _opener
    return self._accessor.open(self, flags, mode)
  File "/opt/python/3.6.7/lib/python3.6/pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
FileNotFoundError: [Errno 2] No such file or directory: '~/.bashrc'
```

**Comment by jwodder** [comment]
This is happening because the tilde isn't expanded.  I believe that changing the script to expand tildes would be the wrong way to go, as the user should be expected to pass in a valid path in the first place; the Travis config should instead be corrected to use `$HOME` instead of `~`.

**Comment by yarikoptic** [comment]
> I believe that changing the script to expand tildes would be the wrong way to go

I wonder why? do you mean that we should allow users to have `~` is their filenames/paths?

**Comment by jwodder** [comment]
@yarikoptic I mean that it should be the user's responsibility to pass in a fully-expanded path.  I can't think of a situation where the user would be forced to pass in an unexpanded tilde that they want the script to expand.

**Comment by yarikoptic** [comment]
ok, let's keep as is then, I can do `$HOME`
