### ISSUE TITLE
git-annex -m conda installation fails in CI

### ISSUE THREAD

**Issue by adswa** [datalad/datalad-installer#206]
Seen in https://github.com/datalad/datalad/pull/7661 (for any runs I didn't cancel fast enough)

```
Run pip install datalad-installer
bash: cannot set terminal process group (597): Inappropriate ioctl for device
bash: no job control in this shell
Collecting datalad-installer
  Downloading datalad_installer-1.0.5-py3-none-any.whl.metadata (23 kB)
Downloading datalad_installer-1.0.5-py3-none-any.whl (31 kB)
Installing collected packages: datalad-installer
Successfully installed datalad-installer-1.0.5
2024-09-17T13:16:49+0000 [INFO    ] datalad_installer: Installing Miniconda
2024-09-17T13:16:49+0000 [INFO    ] datalad_installer: Version: latest
2024-09-17T13:16:49+0000 [INFO    ] datalad_installer: Path: /tmp/dl-miniconda-t13yyvgm
2024-09-17T13:16:49+0000 [INFO    ] datalad_installer: Batch: True
2024-09-17T13:16:49+0000 [INFO    ] datalad_installer: Channels: ['conda-forge']
2024-09-17T13:16:49+0000 [INFO    ] datalad_installer: Spec: None
2024-09-17T13:16:49+0000 [INFO    ] datalad_installer: Python Match: minor
2024-09-17T13:16:49+0000 [INFO    ] datalad_installer: Extra args: None
2024-09-17T13:16:49+0000 [INFO    ] datalad_installer: Downloading and running miniconda installer
2024-09-17T13:16:49+0000 [INFO    ] datalad_installer: Downloading https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
2024-09-17T13:16:50+0000 [INFO    ] datalad_installer: Installing miniconda in /tmp/dl-miniconda-t13yyvgm
2024-09-17T13:16:50+0000 [INFO    ] datalad_installer: Running: bash /tmp/tmpt7wziqzu/Miniconda3-latest-Linux-x86_64.sh -p /tmp/dl-miniconda-t13yyvgm -s -b
PREFIX=/tmp/dl-miniconda-t13yyvgm
Unpacking payload ...

Installing base environment...

Preparing transaction: ...working... done
Executing transaction: ...working... done
installation finished.
2024-09-17T13:16:57+0000 [INFO    ] datalad_installer: Running: /tmp/dl-miniconda-t13yyvgm/bin/conda --version
2024-09-17T13:16:57+0000 [INFO    ] datalad_installer: Running: /tmp/dl-miniconda-t13yyvgm/bin/conda install --yes --channel conda-forge python=3.11
Channels:
 - conda-forge
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /tmp/dl-miniconda-t13yyvgm

  added / updated specs:
    - python=3.11


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    _libgcc_mutex-0.1          |      conda_forge           3 KB  conda-forge
    _openmp_mutex-4.5          |            2_gnu          23 KB  conda-forge
    anaconda-anon-usage-0.4.4  |py311hfc0e8ea_100          29 KB
    boltons-24.0.0             |     pyhd8ed1ab_0         291 KB  conda-forge
    brotli-python-1.1.0        |  py311hfdbb021_2         342 KB  conda-forge
    ca-certificates-2024.8.30  |       hbcca054_0         155 KB  conda-forge
    certifi-2024.8.30          |     pyhd8ed1ab_0         160 KB  conda-forge
    cffi-1.17.1                |  py311hf29c0ef_0         295 KB  conda-forge
    colorama-0.4.6             |     pyhd8ed1ab_0          25 KB  conda-forge
    conda-24.7.1               |  py311h38be061_0         1.2 MB  conda-forge
    conda-content-trust-0.2.0  |     pyhd8ed1ab_0          57 KB  conda-forge
    conda-package-handling-2.3.0|     pyh7900ff3_0         250 KB  conda-forge
    conda-package-streaming-0.10.0|     pyhd8ed1ab_0          19 KB  conda-forge
    cryptography-43.0.1        |  py311hafd3f86_0         1.4 MB  conda-forge
    distro-1.9.0               |     pyhd8ed1ab_0          41 KB  conda-forge
    expat-2.6.3                |       h5888daf_0         135 KB  conda-forge
    frozendict-2.4.4           |  py311h331c9d8_0          31 KB  conda-forge
    h2-4.1.0                   |     pyhd8ed1ab_0          46 KB  conda-forge
    hpack-4.0.0                |     pyh9f0ad1d_0          25 KB  conda-forge
    hyperframe-6.0.1           |     pyhd8ed1ab_0          14 KB  conda-forge
    icu-75.1                   |       he02047a_0        11.6 MB  conda-forge
    idna-3.10                  |     pyhd8ed1ab_0          49 KB  conda-forge
    jsonpatch-1.33             |     pyhd8ed1ab_0          17 KB  conda-forge
    libarchive-3.7.4           |       hfca40fe_0         851 KB  conda-forge
    libcurl-8.1.2              |       h409715c_0         364 KB  conda-forge
    libexpat-2.6.3             |       h5888daf_0          72 KB  conda-forge
    libgcc-14.1.0              |       h77fa898_1         827 KB  conda-forge
    libgcc-ng-14.1.0           |       h69a702a_1          51 KB  conda-forge
    libgomp-14.1.0             |       h77fa898_1         449 KB  conda-forge
    libiconv-1.17              |       hd590300_2         689 KB  conda-forge
    libmamba-1.5.8             |       hfe524e5_3         1.8 MB
    libmambapy-1.5.8           |  py311h2dafd23_3         334 KB
    libnghttp2-1.52.0          |       h61bc06f_0         608 KB  conda-forge
    libnsl-2.0.1               |       hd590300_0          33 KB  conda-forge
    libsolv-0.7.30             |       h3509ff9_0         460 KB  conda-forge
    libsqlite-3.46.1           |       hadc24fc_0         845 KB  conda-forge
    libssh2-1.11.0             |       h0841786_0         265 KB  conda-forge
    libstdcxx-14.1.0           |       hc0a3c3a_1         3.7 MB  conda-forge
    libstdcxx-ng-14.1.0        |       h4852527_1          51 KB  conda-forge
    libuuid-2.38.1             |       h0b41bf4_0          33 KB  conda-forge
    libxcrypt-4.4.36           |       hd590300_1          98 KB  conda-forge
    libxml2-2.12.7             |       he7c6b58_4         691 KB  conda-forge
    libzlib-1.3.1              |       h4ab18f5_1          60 KB  conda-forge
    lzo-2.10                   |    hd590300_1001         167 KB  conda-forge
    menuinst-2.1.2             |  py311h38be061_1         167 KB  conda-forge
    ncurses-6.5                |       he02047a_1         868 KB  conda-forge
    openssl-3.3.2              |       hb9d3cd8_0         2.8 MB  conda-forge
    packaging-24.1             |     pyhd8ed1ab_0          49 KB  conda-forge
    pcre2-10.44                |       hba22ea6_2         930 KB  conda-forge
    pip-24.2                   |     pyh8b19718_1         1.2 MB  conda-forge
    platformdirs-4.3.3         |     pyhd8ed1ab_0          20 KB  conda-forge
    pluggy-1.5.0               |     pyhd8ed1ab_0          23 KB  conda-forge
    pybind11-abi-4             |       hd8ed1ab_3          10 KB  conda-forge
    pycosat-0.6.6              |  py311h459d7ec_0          86 KB  conda-forge
    pysocks-1.7.1              |     pyha2e5f31_6          19 KB  conda-forge
    python-3.11.10             |hc5c86c4_0_cpython        29.2 MB  conda-forge
    python_abi-3.11            |          5_cp311           6 KB  conda-forge
    requests-2.32.3            |     pyhd8ed1ab_0          57 KB  conda-forge
    ruamel.yaml-0.18.6         |  py311h459d7ec_0         267 KB  conda-forge
    ruamel.yaml.clib-0.2.8     |  py311h459d7ec_0         133 KB  conda-forge
    setuptools-73.0.1          |     pyhd8ed1ab_0         1.4 MB  conda-forge
    sqlite-3.46.1              |       h9eae976_0         839 KB  conda-forge
    tk-8.6.13                  |noxft_h4845f30_101         3.2 MB  conda-forge
    tqdm-4.66.5                |     pyhd8ed1ab_0          87 KB  conda-forge
    truststore-0.9.2           |     pyhd8ed1ab_0          21 KB  conda-forge
    urllib3-2.2.3              |     pyhd8ed1ab_0          96 KB  conda-forge
    wheel-0.44.0               |     pyhd8ed1ab_0          57 KB  conda-forge
    zlib-1.3.1                 |       h4ab18f5_1          91 KB  conda-forge
    zstandard-0.23.0           |  py311hbc35293_1         408 KB  conda-forge
    zstd-1.5.6                 |       ha6fb4c9_0         542 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        70.8 MB

The following NEW packages will be INSTALLED:

  colorama           conda-forge/noarch::colorama-0.4.6-pyhd8ed1ab_0 
  h2                 conda-forge/noarch::h2-4.1.0-pyhd8ed1ab_0 
  hpack              conda-forge/noarch::hpack-4.0.0-pyh9f0ad1d_0 
  hyperframe         conda-forge/noarch::hyperframe-6.0.1-pyhd8ed1ab_0 
  libexpat           conda-forge/linux-64::libexpat-2.6.3-h5888daf_0 
  libgcc             conda-forge/linux-64::libgcc-14.1.0-h77fa898_1 
  libiconv           conda-forge/linux-64::libiconv-1.17-hd590300_2 
  libnsl             conda-forge/linux-64::libnsl-2.0.1-hd590300_0 
  libsqlite          conda-forge/linux-64::libsqlite-3.46.1-hadc24fc_0 
  libstdcxx          conda-forge/linux-64::libstdcxx-14.1.0-hc0a3c3a_1 
  libxcrypt          conda-forge/linux-64::libxcrypt-4.4.36-hd590300_1 
  libzlib            conda-forge/linux-64::libzlib-1.3.1-h4ab18f5_1 
  lzo                conda-forge/linux-64::lzo-2.10-hd590300_1001 
  python_abi         conda-forge/linux-64::python_abi-3.11-5_cp311 
  ruamel.yaml.clib   conda-forge/linux-64::ruamel.yaml.clib-0.2.8-py311h459d7ec_0 

The following packages will be UPDATED:

  boltons            pkgs/main/linux-64::boltons-23.0.0-py~ --> conda-forge/noarch::boltons-24.0.0-pyhd8ed1ab_0 
  brotli-python      pkgs/main::brotli-python-1.0.9-py312h~ --> conda-forge::brotli-python-1.1.0-py311hfdbb021_2 
  ca-certificates    pkgs/main::ca-certificates-2024.7.2-h~ --> conda-forge::ca-certificates-2024.8.30-hbcca054_0 
  certifi            pkgs/main/linux-64::certifi-2024.7.4-~ --> conda-forge/noarch::certifi-2024.8.30-pyhd8ed1ab_0 
  cffi               pkgs/main::cffi-1.16.0-py312h5eee18b_1 --> conda-forge::cffi-1.17.1-py311hf29c0ef_0 
  cryptography       pkgs/main::cryptography-42.0.5-py312h~ --> conda-forge::cryptography-43.0.1-py311hafd3f86_0 
  expat                   pkgs/main::expat-2.6.2-h6a678d5_0 --> conda-forge::expat-2.6.3-h5888daf_0 
  frozendict         pkgs/main::frozendict-2.4.2-py312h06a~ --> conda-forge::frozendict-2.4.4-py311h331c9d8_0 
  icu                        pkgs/main::icu-73.1-h6a678d5_0 --> conda-forge::icu-75.1-he02047a_0 
  idna               pkgs/main/linux-64::idna-3.7-py312h06~ --> conda-forge/noarch::idna-3.10-pyhd8ed1ab_0 
  libarchive         pkgs/main::libarchive-3.6.2-hfab0078_4 --> conda-forge::libarchive-3.7.4-hfca40fe_0 
  libgcc-ng          pkgs/main::libgcc-ng-11.2.0-h1234567_1 --> conda-forge::libgcc-ng-14.1.0-h69a702a_1 
  libgomp              pkgs/main::libgomp-11.2.0-h1234567_1 --> conda-forge::libgomp-14.1.0-h77fa898_1 
  libmamba                                 1.5.8-hfe524e5_2 --> 1.5.8-hfe524e5_3 
  libmambapy                          1.5.8-py312h2dafd23_2 --> 1.5.8-py311h2dafd23_3 
  libsolv              pkgs/main::libsolv-0.7.24-he621ea3_1 --> conda-forge::libsolv-0.7.30-h3509ff9_0 
  libstdcxx-ng       pkgs/main::libstdcxx-ng-11.2.0-h12345~ --> conda-forge::libstdcxx-ng-14.1.0-h4852527_1 
  libuuid              pkgs/main::libuuid-1.41.5-h5eee18b_0 --> conda-forge::libuuid-2.38.1-h0b41bf4_0 
  menuinst           pkgs/main::menuinst-2.1.2-py312h06a43~ --> conda-forge::menuinst-2.1.2-py311h38be061_1 
  ncurses                 pkgs/main::ncurses-6.4-h6a678d5_0 --> conda-forge::ncurses-6.5-he02047a_1 
  openssl              pkgs/main::openssl-3.0.14-h5eee18b_0 --> conda-forge::openssl-3.3.2-hb9d3cd8_0 
  pcre2                   pkgs/main::pcre2-10.42-hebb0a14_1 --> conda-forge::pcre2-10.44-hba22ea6_2 
  pip                pkgs/main/linux-64::pip-24.2-py312h06~ --> conda-forge/noarch::pip-24.2-pyh8b19718_1 
  platformdirs       pkgs/main/linux-64::platformdirs-3.10~ --> conda-forge/noarch::platformdirs-4.3.3-pyhd8ed1ab_0 
  pluggy             pkgs/main/linux-64::pluggy-1.0.0-py31~ --> conda-forge/noarch::pluggy-1.5.0-pyhd8ed1ab_0 
  pysocks            pkgs/main/linux-64::pysocks-1.7.1-py3~ --> conda-forge/noarch::pysocks-1.7.1-pyha2e5f31_6 
  ruamel.yaml        pkgs/main::ruamel.yaml-0.17.21-py312h~ --> conda-forge::ruamel.yaml-0.18.6-py311h459d7ec_0 
  setuptools         pkgs/main/linux-64::setuptools-72.1.0~ --> conda-forge/noarch::setuptools-73.0.1-pyhd8ed1ab_0 
  sqlite                pkgs/main::sqlite-3.45.3-h5eee18b_0 --> conda-forge::sqlite-3.46.1-h9eae976_0 
  tqdm               pkgs/main/linux-64::tqdm-4.66.4-py312~ --> conda-forge/noarch::tqdm-4.66.5-pyhd8ed1ab_0 
  truststore         pkgs/main/linux-64::truststore-0.8.0-~ --> conda-forge/noarch::truststore-0.9.2-pyhd8ed1ab_0 
  urllib3            pkgs/main/linux-64::urllib3-2.2.2-py3~ --> conda-forge/noarch::urllib3-2.2.3-pyhd8ed1ab_0 
  wheel              pkgs/main/linux-64::wheel-0.43.0-py31~ --> conda-forge/noarch::wheel-0.44.0-pyhd8ed1ab_0 
  zlib                    pkgs/main::zlib-1.2.13-h5eee18b_1 --> conda-forge::zlib-1.3.1-h4ab18f5_1 
  zstandard          pkgs/main::zstandard-0.22.0-py312h2c3~ --> conda-forge::zstandard-0.23.0-py311hbc35293_1 
  zstd                     pkgs/main::zstd-1.5.5-hc292b87_2 --> conda-forge::zstd-1.5.6-ha6fb4c9_0 

The following packages will be SUPERSEDED by a higher-priority channel:

  _libgcc_mutex           pkgs/main::_libgcc_mutex-0.1-main --> conda-forge::_libgcc_mutex-0.1-conda_forge 
  _openmp_mutex          pkgs/main::_openmp_mutex-5.1-1_gnu --> conda-forge::_openmp_mutex-4.5-2_gnu 
  conda              pkgs/main::conda-24.7.1-py312h06a4308~ --> conda-forge::conda-24.7.1-py311h38be061_0 
  conda-content-tru~ pkgs/main/linux-64::conda-content-tru~ --> conda-forge/noarch::conda-content-trust-0.2.0-pyhd8ed1ab_0 
  conda-package-han~ pkgs/main/linux-64::conda-package-han~ --> conda-forge/noarch::conda-package-handling-2.3.0-pyh7900ff3_0 
  conda-package-str~ pkgs/main/linux-64::conda-package-str~ --> conda-forge/noarch::conda-package-streaming-0.10.0-pyhd8ed1ab_0 
  distro             pkgs/main/linux-64::distro-1.9.0-py31~ --> conda-forge/noarch::distro-1.9.0-pyhd8ed1ab_0 
  jsonpatch          pkgs/main/linux-64::jsonpatch-1.33-py~ --> conda-forge/noarch::jsonpatch-1.33-pyhd8ed1ab_0 
  libcurl               pkgs/main::libcurl-8.7.1-h251f7ec_0 --> conda-forge::libcurl-8.1.2-h409715c_0 
  libnghttp2         pkgs/main::libnghttp2-1.57.0-h2d74bed~ --> conda-forge::libnghttp2-1.52.0-h61bc06f_0 
  libssh2              pkgs/main::libssh2-1.11.0-h251f7ec_0 --> conda-forge::libssh2-1.11.0-h0841786_0 
  libxml2              pkgs/main::libxml2-2.13.1-hfdd30dd_2 --> conda-forge::libxml2-2.12.7-he7c6b58_4 
  packaging          pkgs/main/linux-64::packaging-24.1-py~ --> conda-forge/noarch::packaging-24.1-pyhd8ed1ab_0 
  pybind11-abi         pkgs/main::pybind11-abi-5-hd3eb1b0_0 --> conda-forge::pybind11-abi-4-hd8ed1ab_3 
  pycosat            pkgs/main::pycosat-0.6.6-py312h5eee18~ --> conda-forge::pycosat-0.6.6-py311h459d7ec_0 
  python                pkgs/main::python-3.12.4-h5148396_1 --> conda-forge::python-3.11.10-hc5c86c4_0_cpython 
  requests           pkgs/main/linux-64::requests-2.32.3-p~ --> conda-forge/noarch::requests-2.32.3-pyhd8ed1ab_0 
  tk                        pkgs/main::tk-8.6.14-h39e8969_0 --> conda-forge::tk-8.6.13-noxft_h4845f30_101 

The following packages will be DOWNGRADED:

  anaconda-anon-usa~                0.4.4-py312hfc0e8ea_100 --> 0.4.4-py311hfc0e8ea_100 



Downloading and Extracting Packages: ...working... done
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
2024-09-17T13:17:18+0000 [INFO    ] datalad_installer: Installing git-annex via conda
2024-09-17T13:17:18+0000 [INFO    ] datalad_installer: Environment: None
2024-09-17T13:17:18+0000 [INFO    ] datalad_installer: Version: None
2024-09-17T13:17:18+0000 [INFO    ] datalad_installer: Extra args: None
2024-09-17T13:17:18+0000 [INFO    ] datalad_installer: Running: /tmp/dl-miniconda-t13yyvgm/bin/conda install -q -c conda-forge -y git-annex
Error while loading conda entry point: conda-libmamba-solver (libarchive.so.20: cannot open shared object file: No such file or directory)

CondaValueError: You have chosen a non-default solver backend (libmamba) but it was not recognized. Choose one of: classic

2024-09-17T13:17:18+0000 [ERROR   ] datalad_installer: Command failed with exit status 1; sleeping and retrying
2024-09-17T13:17:23+0000 [INFO    ] datalad_installer: Running: /tmp/dl-miniconda-t13yyvgm/bin/conda install -q -c conda-forge -y git-annex
Error while loading conda entry point: conda-libmamba-solver (libarchive.so.20: cannot open shared object file: No such file or directory)

CondaValueError: You have chosen a non-default solver backend (libmamba) but it was not recognized. Choose one of: classic

2024-09-17T13:17:23+0000 [ERROR   ] datalad_installer: Command failed with exit status 1; sleeping and retrying
2024-09-17T13:17:28+0000 [INFO    ] datalad_installer: Running: /tmp/dl-miniconda-t13yyvgm/bin/conda install -q -c conda-forge -y git-annex
Error while loading conda entry point: conda-libmamba-solver (libarchive.so.20: cannot open shared object file: No such file or directory)

CondaValueError: You have chosen a non-default solver backend (libmamba) but it was not recognized. Choose one of: classic

2024-09-17T13:17:29+0000 [ERROR   ] datalad_installer: Command failed with exit status 1; sleeping and retrying
2024-09-17T13:17:34+0000 [INFO    ] datalad_installer: Running: /tmp/dl-miniconda-t13yyvgm/bin/conda install -q -c conda-forge -y git-annex
Error while loading conda entry point: conda-libmamba-solver (libarchive.so.20: cannot open shared object file: No such file or directory)

CondaValueError: You have chosen a non-default solver backend (libmamba) but it was not recognized. Choose one of: classic

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.9/x64/bin/datalad-installer", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/datalad_installer.py", line 3096, in main
    return manager.main(argv)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/datalad_installer.py", line 746, in main
    self.addcomponent(name=cr.name, **cr.kwargs)
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/datalad_installer.py", line 785, in addcomponent
    component(self).provide(**kwargs)
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/datalad_installer.py", line 1343, in provide
    bins = self.get_installer(method).install(self.NAME, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/datalad_installer.py", line 1475, in install
    bindir = self.install_package(package, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/datalad_installer.py", line 1966, in install_package
    runcmd(*cmd)
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/datalad_installer.py", line 2818, in runcmd
    return subprocess.run(arglist, check=True, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/tmp/dl-miniconda-t13yyvgm/bin/conda', 'install', '-q', '-c', 'conda-forge', '-y', 'git-annex']' returned non-zero exit status 1.
Error: Process completed with exit code 1.
```

**Comment by yarikoptic** [comment]
seems has started recently
```
datalad@smaug:/mnt/datasets/datalad/ci/logs/2024/09$ git grep -l 'You have chosen a non-default solver backend ' | head
10/push/maint/b55d8b7/github-Test-229-failed/3_test (3.11, not, 10, [annex] stalldetection = 1KB120s, min.txt
10/push/maint/b55d8b7/github-Test-229-failed/4_test (3.11, 10, [annex] stalldetection = 1KB120s, minicond.txt
10/push/maint/b55d8b7/github-Test-229-failed/test (3.11, 10, [annex] stalldetection = 1KB120s, miniconda --channel conda-forge --python/10_Install git-annex.txt
10/push/maint/b55d8b7/github-Test-229-failed/test (3.11, not, 10, [annex] stalldetection = 1KB120s, miniconda --channel conda-forge --p/10_Install git-annex.txt
11/cron/20240911T062223/b55d8b7/github-Test-230-failed/3_test (3.11, not, 10, [annex] stalldetection = 1KB120s, min.txt
11/cron/20240911T062223/b55d8b7/github-Test-230-failed/4_test (3.11, 10, [annex] stalldetection = 1KB120s, minicond.txt
11/cron/20240911T062223/b55d8b7/github-Test-230-failed/test (3.11, 10, [annex] stalldetection = 1KB120s, miniconda --channel conda-forge --python/10_Install git-annex.txt
11/cron/20240911T062223/b55d8b7/github-Test-230-failed/test (3.11, not, 10, [annex] stalldetection = 1KB120s, miniconda --channel conda-forge --p/10_Install git-annex.txt
12/cron/20240912T062239/b55d8b7/github-Test-231-failed/3_test (3.11, not, 10, [annex] stalldetection = 1KB120s, min.txt
12/cron/20240912T062239/b55d8b7/github-Test-231-failed/4_test (3.11, 10, [annex] stalldetection = 1KB120s, minicond.txt
```
googled myself into https://stackoverflow.com/questions/77617946/solve-conda-libmamba-solver-libarchive-so-19-error-after-updating-conda-to-23 which pointed to
- https://github.com/conda/conda-libmamba-solver/issues/283

and boils down to libmamba coming from main archive while the rest from conda-forge.  Workarounds are multitude (e.g. adding `--solver=classic`) but that might override configuration in some existing environment...  For better sense of situation filed

- https://github.com/conda/constructor/issues/862

but if I don't hear back, we might need to add a workaround of some kind (e.g. set to "classic" resolved in our created miniconda env), or add handling of crash/error and providing `--solver=classic` upon re-invocation (I recall us already doing some conditional treatments of errors).

**Comment by yarikoptic** [comment]
ok, besides adding `miniforge` and possibly other installers, I think it might be worth adding an option to miniconda installer part which would allow to specify config options, so we could simply either enforce specific resolver or enable only conda-forge and forget about anaconda: e.g. `--channels` so that if it doesn't include `defaults` we do

```
conda config --remove channels defaults
```
and then add all provided, e.g.
```
conda config --add channels conda-forge
```

I think this way we could then enforce in our CI installation consistent use of conda-forge.

**Comment by yarikoptic** [comment]
- #222 

presumably addressed that by switching to miniforge. Let's see how that goes
