### ISSUE TITLE
Add Windows support for installing git-annex and datalad

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-installer#3]
As of 9e011b7c178a851b669d78070d9ee24986b70837  in #1 `git-annex` cannot be installed using installer:

<details>
<summary>there is no git-annex in conda yet, but if conda is chosen (e.g. via `auto`) it would fail </summary> 

```shell
(datalad-3) C:\Users\DataLad\PycharmProjects\datalad-installer>python src\datalad_installer.py git-annex
2021-01-05T13:20:54-0800 [INFO    ] datalad_installer Writing environment modifications to C:\Users\DataLad\AppData\Local\Temp\dl-env-s_1dqjqf.sh
2021-01-05T13:20:54-0800 [INFO    ] datalad_installer Installing git-annex via conda
2021-01-05T13:20:54-0800 [INFO    ] datalad_installer Running: 'C:\Users\DataLad\miniconda3\condabin\conda.BAT' info --base
2021-01-05T13:20:55-0800 [INFO    ] datalad_installer Environment: None
2021-01-05T13:20:55-0800 [INFO    ] datalad_installer Version: None
2021-01-05T13:20:55-0800 [INFO    ] datalad_installer Extra args: None
2021-01-05T13:20:55-0800 [INFO    ] datalad_installer Running: 'C:\Users\DataLad\miniconda3\bin\conda' install -q -c conda-forge -y git-annex
Traceback (most recent call last):
  File "src\datalad_installer.py", line 1642, in <module>
    sys.exit(main(sys.argv))
  File "src\datalad_installer.py", line 1638, in main
    return manager.main(argv)
  File "src\datalad_installer.py", line 597, in main
    self.addcomponent(name=cr.name, **cr.kwargs)
  File "src\datalad_installer.py", line 633, in addcomponent
    component(self).provide(**kwargs)
  File "src\datalad_installer.py", line 957, in provide
    bins = installer.install(self.NAME, **kwargs)
  File "src\datalad_installer.py", line 1038, in install
    bindir = self.install_package(package, **kwargs)
  File "src\datalad_installer.py", line 1442, in install_package
    runcmd(*cmd)
  File "src\datalad_installer.py", line 1614, in runcmd
    return subprocess.run(arglist, check=True, **kwargs)
  File "C:\Users\DataLad\miniconda3\envs\datalad-3\lib\subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\DataLad\miniconda3\envs\datalad-3\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\DataLad\miniconda3\envs\datalad-3\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified  
```
</details>

similarly installation of datalad via conda -- it tries to use `C:\Users\DataLad\miniconda3\bin\conda` but there is no such thing on Windows.

<details>
<summary>and it would raise MethodNotSupportedError if I specify to install from our datalad/git-annex builds:</summary> 

```shell
(datalad-3) C:\Users\DataLad\PycharmProjects\datalad-installer>python src\datalad_installer.py git-annex --method datalad/git-annex
2021-01-05T13:23:50-0800 [INFO    ] datalad_installer Writing environment modifications to C:\Users\DataLad\AppData\Local\Temp\dl-env-9zb76rn_.sh
Traceback (most recent call last):
  File "src\datalad_installer.py", line 1642, in <module>
    sys.exit(main(sys.argv))
  File "src\datalad_installer.py", line 1638, in main
    return manager.main(argv)
  File "src\datalad_installer.py", line 597, in main
    self.addcomponent(name=cr.name, **cr.kwargs)
  File "src\datalad_installer.py", line 633, in addcomponent
    component(self).provide(**kwargs)
  File "src\datalad_installer.py", line 952, in provide
    bins = self.get_installer(method).install(self.NAME, **kwargs)
  File "src\datalad_installer.py", line 1031, in install
    self.assert_supported_system()
  File "src\datalad_installer.py", line 1497, in assert_supported_system
    raise MethodNotSupportedError(f"{systype} OS not supported")
__main__.MethodNotSupportedError: Windows OS not supported
```
</details>

**Comment by mih** [comment]
FTR: Here is what I do to install git-annex on windows with appveyor:

```
% cat tools/ci/appveyor_install_git-annex.bat
REM Install git-annex
appveyor DownloadFile http://datasets.datalad.org/datalad/packages/windows/git-annex-installer_8.20201127+git11-g3be9dc6e1_x64.exe -FileName C:\TMP\git-annex-installer.exe
REM 7z is preinstalled in all images
REM Extract directly into system Git installation
7z x -aoa -o"C:\\Program Files\Git" C:\TMP\git-annex-installer.exe
```

DataLad itself can be installed via `pip` with no issues, as far as I am aware.

**Comment by yarikoptic** [comment]
Thanks!

> DataLad itself can be installed via `pip` with no issues, as far as I am aware.

great! as well as via `conda`.  So would be good to have multiple methods ;)

**Comment by jwodder** [comment]
To-do list for this issue:

- [ ] Mark conda on Windows as an unsupported system for installing git-annex
- [x] Support installation of Datalad via conda on Windows (#9, #17)
- [ ] Support installing git-annex via datalad/git-annex on Windows
- [ ] Add an installation method for installing git-annex on Windows by downloading from <http://datasets.datalad.org/datalad/packages/windows/>

@yarikoptic Anything else?

**Comment by yarikoptic** [comment]
I think that should be it for now... We are yet to figure out I guess how to make `datalad_installer.py datalad` do "the right" thing across all OSes (e.g. here we could default to installing git-annex from http://datasets.datalad.org/datalad/packages/windows/), but that is IMHO some future (and only tentative) development .
