### ISSUE TITLE
windows user feedback

### ISSUE THREAD

**Issue by mih** [datalad/datalad-installer#43]
This is a protocol of how things feel for a wannabe windows-user (me!) with a system that has Python and Git already, aiming to get datalad running.

First I want git-annex.

```
C:\Users\datalad>datalad-installer git-annex
2021-03-06T16:43:32+0100 [INFO    ] datalad_installer Writing environment modifications to C:\Users\datalad\AppData\Local\Temp\dl-env-zvzy88jc.sh
Traceback (most recent call last):
  File "c:\users\datalad\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\datalad\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\datalad\AppData\Local\Programs\Python\Python39\Scripts\datalad-installer.exe\__main__.py", line 7, in <module>
  File "c:\users\datalad\appdata\local\programs\python\python39\lib\site-packages\datalad_installer.py", line 1788, in main
    return manager.main(argv)
  File "c:\users\datalad\appdata\local\programs\python\python39\lib\site-packages\datalad_installer.py", line 657, in main
    self.addcomponent(name=cr.name, **cr.kwargs)
  File "c:\users\datalad\appdata\local\programs\python\python39\lib\site-packages\datalad_installer.py", line 690, in addcomponent
    component(self).provide(**kwargs)
  File "c:\users\datalad\appdata\local\programs\python\python39\lib\site-packages\datalad_installer.py", line 1044, in provide
    raise RuntimeError(f"No viable installation method for {self.NAME}")
RuntimeError: No viable installation method for git-annex
```

If I disagree, I get further ;-)

```
C:\Users\datalad>datalad-installer git-annex -m datalad/packages
2021-03-06T16:43:57+0100 [INFO    ] datalad_installer Writing environment modifications to C:\Users\datalad\AppData\Local\Temp\dl-env-2n7ihsjb.sh
2021-03-06T16:43:57+0100 [INFO    ] datalad_installer Installing git-annex via datalad/packages
2021-03-06T16:43:57+0100 [INFO    ] datalad_installer Version: None
2021-03-06T16:43:57+0100 [INFO    ] datalad_installer Downloading https://datasets.datalad.org/datalad/packages/windows/git-annex-installer_latest-snapshot_x64.exe
2021-03-06T16:44:03+0100 [INFO    ] datalad_installer Running: 'C:\Users\datalad\AppData\Local\Temp\tmp034rr3ty\git-annex-installer_latest-snapshot_x64.exe' /S
Traceback (most recent call last):
  File "c:\users\datalad\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\datalad\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\datalad\AppData\Local\Programs\Python\Python39\Scripts\datalad-installer.exe\__main__.py", line 7, in <module>
  File "c:\users\datalad\appdata\local\programs\python\python39\lib\site-packages\datalad_installer.py", line 1788, in main
    return manager.main(argv)
  File "c:\users\datalad\appdata\local\programs\python\python39\lib\site-packages\datalad_installer.py", line 657, in main
    self.addcomponent(name=cr.name, **cr.kwargs)
  File "c:\users\datalad\appdata\local\programs\python\python39\lib\site-packages\datalad_installer.py", line 690, in addcomponent
    component(self).provide(**kwargs)
  File "c:\users\datalad\appdata\local\programs\python\python39\lib\site-packages\datalad_installer.py", line 1032, in provide
    bins = self.get_installer(method).install(self.NAME, **kwargs)
  File "c:\users\datalad\appdata\local\programs\python\python39\lib\site-packages\datalad_installer.py", line 1118, in install
    bindir = self.install_package(package, **kwargs)
  File "c:\users\datalad\appdata\local\programs\python\python39\lib\site-packages\datalad_installer.py", line 1687, in install_package
    runcmd(exepath, "/S")
  File "c:\users\datalad\appdata\local\programs\python\python39\lib\site-packages\datalad_installer.py", line 1756, in runcmd
    return subprocess.run(arglist, check=True, **kwargs)
  File "c:\users\datalad\appdata\local\programs\python\python39\lib\subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "c:\users\datalad\appdata\local\programs\python\python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "c:\users\datalad\appdata\local\programs\python\python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 740] The requested operation requires elevation
```

Aha! I have read the documentation in full, and my main laptop runs Linux, so I use this info

```
  --sudo [ask|error|ok]           How to handle sudo commands [default: ask]
```

fully aware that I have no sudo, but something similar is needed, and run

```
C:\Users\datalad>datalad-installer --sudo ok git-annex -m datalad/packages
2021-03-06T16:50:59+0100 [INFO    ] datalad_installer Writing environment modifications to C:\Users\datalad\AppData\Local\Temp\dl-env-dwsma27f.sh
2021-03-06T16:50:59+0100 [INFO    ] datalad_installer Installing git-annex via datalad/packages
2021-03-06T16:50:59+0100 [INFO    ] datalad_installer Version: None
2021-03-06T16:50:59+0100 [INFO    ] datalad_installer Downloading https://datasets.datalad.org/datalad/packages/windows/git-annex-installer_latest-snapshot_x64.exe
2021-03-06T16:51:07+0100 [INFO    ] datalad_installer Running: 'C:\Users\datalad\AppData\Local\Temp\tmpf4523rj7\git-annex-installer_latest-snapshot_x64.exe' /S
Traceback (most recent call last):
  File "c:\users\datalad\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\datalad\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\datalad\AppData\Local\Programs\Python\Python39\Scripts\datalad-installer.exe\__main__.py", line 7, in <module>
  File "c:\users\datalad\appdata\local\programs\python\python39\lib\site-packages\datalad_installer.py", line 1788, in main
    return manager.main(argv)
  File "c:\users\datalad\appdata\local\programs\python\python39\lib\site-packages\datalad_installer.py", line 657, in main
    self.addcomponent(name=cr.name, **cr.kwargs)
  File "c:\users\datalad\appdata\local\programs\python\python39\lib\site-packages\datalad_installer.py", line 690, in addcomponent
    component(self).provide(**kwargs)
  File "c:\users\datalad\appdata\local\programs\python\python39\lib\site-packages\datalad_installer.py", line 1032, in provide
    bins = self.get_installer(method).install(self.NAME, **kwargs)
  File "c:\users\datalad\appdata\local\programs\python\python39\lib\site-packages\datalad_installer.py", line 1118, in install
    bindir = self.install_package(package, **kwargs)
  File "c:\users\datalad\appdata\local\programs\python\python39\lib\site-packages\datalad_installer.py", line 1687, in install_package
    runcmd(exepath, "/S")
  File "c:\users\datalad\appdata\local\programs\python\python39\lib\site-packages\datalad_installer.py", line 1756, in runcmd
    return subprocess.run(arglist, check=True, **kwargs)
  File "c:\users\datalad\appdata\local\programs\python\python39\lib\subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "c:\users\datalad\appdata\local\programs\python\python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "c:\users\datalad\appdata\local\programs\python\python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 740] The requested operation requires elevation
```

OK, `--sudo ok` really has no impact, maybe because there is no sudo.

But I am not giving up! I open an admin-cmd.exe and run

```
C:\WINDOWS\system32>datalad-installer git-annex -m datalad/packages
2021-03-06T16:54:14+0100 [INFO    ] datalad_installer Writing environment modifications to C:\Users\datalad\AppData\Local\Temp\dl-env-06xl69uy.sh
2021-03-06T16:54:14+0100 [INFO    ] datalad_installer Installing git-annex via datalad/packages
2021-03-06T16:54:14+0100 [INFO    ] datalad_installer Version: None
2021-03-06T16:54:14+0100 [INFO    ] datalad_installer Downloading https://datasets.datalad.org/datalad/packages/windows/git-annex-installer_latest-snapshot_x64.exe
2021-03-06T16:54:21+0100 [INFO    ] datalad_installer Running: 'C:\Users\datalad\AppData\Local\Temp\tmpmxwayqxn\git-annex-installer_latest-snapshot_x64.exe' /S
2021-03-06T16:54:23+0100 [INFO    ] datalad_installer git-annex is now installed at C:\Program Files\Git\usr\bin\git-annex.exe
```

BINGO! I have a working git-annex, and did not need `sudo`.

**Comment by yarikoptic** [comment]
awesome -- thank you @mih . So we need to
- default to `datalad/packages` installation method for git-annex on windows
- if elevated privileges needed (catch OSError/WinError 740) -- proceed with `sudo` logic and use smth like https://stackoverflow.com/a/19719292/1265472 for execution.  I would keep it named `--sudo` and just add doc that on windows it means privileges escalation
