### ISSUE TITLE
brew installation of git-annex fails (some times)

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-installer#60]
e.g. https://ci.appveyor.com/project/mih/datalad/builds/39120518/job/lmu5rkrwe3wkh07g
```
==> Downloading https://ghcr.io/v2/homebrew/core/gsasl/manifests/1.8.1
##O#- #                                                                       
curl: (22) The requested URL returned error: 404 
Error: Failed to download resource "gsasl_bottle_manifest"
Download failed: https://ghcr.io/v2/homebrew/core/gsasl/manifests/1.8.1
Traceback (most recent call last):
  File "/Users/appveyor/venv3.8.6/bin/datalad-installer", line 8, in <module>
    sys.exit(main())
  File "/Users/appveyor/venv3.8.6/lib/python3.8/site-packages/datalad_installer.py", line 1788, in main
    return manager.main(argv)
  File "/Users/appveyor/venv3.8.6/lib/python3.8/site-packages/datalad_installer.py", line 657, in main
    self.addcomponent(name=cr.name, **cr.kwargs)
  File "/Users/appveyor/venv3.8.6/lib/python3.8/site-packages/datalad_installer.py", line 690, in addcomponent
    component(self).provide(**kwargs)
  File "/Users/appveyor/venv3.8.6/lib/python3.8/site-packages/datalad_installer.py", line 1037, in provide
    bins = installer.install(self.NAME, **kwargs)
  File "/Users/appveyor/venv3.8.6/lib/python3.8/site-packages/datalad_installer.py", line 1118, in install
    bindir = self.install_package(package, **kwargs)
  File "/Users/appveyor/venv3.8.6/lib/python3.8/site-packages/datalad_installer.py", line 1235, in install_package
    runcmd(*cmd)
  File "/Users/appveyor/venv3.8.6/lib/python3.8/site-packages/datalad_installer.py", line 1756, in runcmd
    return subprocess.run(arglist, check=True, **kwargs)
  File "/Users/appveyor/.localpython3.8.6/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['brew', 'install', 'git-annex']' returned non-zero exit status 1.
Command exited with code 1
Running "on_finish" scripts
while [ -f ~/BLOCK ]; do sleep 5; done
```
preceded by bunch of warnings (dunno if related) such as

```
Warning: Calling `sha256 "digest" => :tag` in a bottle block is deprecated! Use `brew style --fix` on the formula to update the style or use `sha256 tag: "digest"` instead.
Please report this issue to the homebrew/core tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/lua@5.1.rb:18
```
re exception on inability (unauthorized access) to download https://ghcr.io/v2/homebrew/core/gsasl/manifests/1.8.1  i don't know what ghcr.io has to do for brew.

In a good build https://ci.appveyor.com/project/mih/datalad/builds/39119687/job/b5bg6d3jcxwka67s it seems to download another version of that manifest

```
$> grep ghcr.*gsasl log.txt | head
[00:04:40] ==> Downloading https://ghcr.io/v2/homebrew/core/gsasl/manifests/1.10.0
[00:04:42] ==> Downloading https://ghcr.io/v2/homebrew/core/gsasl/blobs/sha256:6f7aa6d0a227
```

**Comment by jwodder** [comment]
@yarikoptic This seems like something that should be reported to Homebrew.

**Comment by yarikoptic** [comment]
Roger that. Could you please report with a link here?

**Comment by jwodder** [comment]
@yarikoptic Brew issues require `brew config` and `brew doctor` output.  That was added in #51, but it hasn't been released yet.

**Comment by yarikoptic** [comment]
Please "cut a release" then unless you see anything which should prevent/postpone it.

**Comment by yarikoptic** [comment]
I then would restart some of the failing runs or just wait for some new PR to fail to provide the info

**Comment by jwodder** [comment]
@yarikoptic Releases can only be made by merging a PR.

**Comment by yarikoptic** [comment]
send a PR with empty commit then.  Or alternatively - https://github.com/datalad/datalad-installer/issues/61 and PR for it could be the one with `release` if it passes, or would provide information needed for this issue if fails similarly.

**Comment by yarikoptic** [comment]
FWIW -- appveyors of datalad were all happy recently, so I guess may be issue went away etc.  I will close this. I also re-pinged @mih to add this repo to the pull of appveyor tasks to run so we see if the setup we have works
