### ISSUE TITLE
Crashes on windows with python 3.8 from miniconda

### ISSUE THREAD

**Issue by mih** [datalad/datalad-installer#9]
Installed via pip as per instructions

```
C:\Users\datalad>datalad_installer
2021-01-07T08:18:22+0100 [INFO    ] datalad_installer Writing environment modifications to C:\Users\datalad\AppData\Local\Temp\dl-env-04uwdey0.sh
2021-01-07T08:18:22+0100 [INFO    ] datalad_installer Installing datalad via conda
2021-01-07T08:18:22+0100 [INFO    ] datalad_installer Running: 'C:\Users\datalad\miniconda3\Library\bin\conda.BAT' info --base
2021-01-07T08:18:23+0100 [INFO    ] datalad_installer Environment: None
2021-01-07T08:18:23+0100 [INFO    ] datalad_installer Version: None
2021-01-07T08:18:23+0100 [INFO    ] datalad_installer Extra args: None
2021-01-07T08:18:23+0100 [INFO    ] datalad_installer Running: 'C:\Users\datalad\miniconda3\bin\conda' install -q -c conda-forge -y datalad
Traceback (most recent call last):
  File "c:\users\datalad\miniconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\datalad\miniconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\datalad\miniconda3\Scripts\datalad_installer.exe\__main__.py", line 7, in <module>
  File "c:\users\datalad\miniconda3\lib\site-packages\datalad_installer.py", line 1638, in main
    return manager.main(argv)
  File "c:\users\datalad\miniconda3\lib\site-packages\datalad_installer.py", line 597, in main
    self.addcomponent(name=cr.name, **cr.kwargs)
  File "c:\users\datalad\miniconda3\lib\site-packages\datalad_installer.py", line 633, in addcomponent
    component(self).provide(**kwargs)
  File "c:\users\datalad\miniconda3\lib\site-packages\datalad_installer.py", line 957, in provide
    bins = installer.install(self.NAME, **kwargs)
  File "c:\users\datalad\miniconda3\lib\site-packages\datalad_installer.py", line 1038, in install
    bindir = self.install_package(package, **kwargs)
  File "c:\users\datalad\miniconda3\lib\site-packages\datalad_installer.py", line 1442, in install_package
    runcmd(*cmd)
  File "c:\users\datalad\miniconda3\lib\site-packages\datalad_installer.py", line 1614, in runcmd
    return subprocess.run(arglist, check=True, **kwargs)
  File "c:\users\datalad\miniconda3\lib\subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "c:\users\datalad\miniconda3\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "c:\users\datalad\miniconda3\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by yarikoptic** [comment]
Windows was not yet "approached" (@jwodder does not even have a "real" Windows laptop ;-)), related if not duplicate -- #3
