### ISSUE TITLE
windows -m datalad/git-annex: NotADirectoryError

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-installer#91]
whenever dialog for allowing to install popsup I click "Yes" but then process fails with an error:

```shell
(datalad-py3.9) C:\Users\DataLad\PycharmProjects\datalad>datalad-installer --sudo ok git-annex -m datalad/git-annex
2021-10-28T19:42:01-0400 [INFO    ] datalad_installer Writing environment modifications to C:\Users\DataLad\AppData\Local\Temp\dl-env-sljvy8s6.sh
2021-10-28T19:42:01-0400 [INFO    ] datalad_installer Installing git-annex via datalad/git-annex
2021-10-28T19:42:01-0400 [INFO    ] datalad_installer Getting artifacts_url from https://api.github.com/repos/datalad/git-annex/actions/workflows/build-windows.yaml/runs?branch=master
2021-10-28T19:42:02-0400 [INFO    ] datalad_installer Getting archive download URL from https://api.github.com/repos/datalad/git-annex/actions/runs/1395456444/artifacts
2021-10-28T19:42:03-0400 [INFO    ] datalad_installer Downloading artifact package from https://api.github.com/repos/datalad/git-annex/actions/artifacts/108109364/zip
2021-10-28T19:42:03-0400 [INFO    ] datalad_installer Downloading https://api.github.com/repos/datalad/git-annex/actions/artifacts/108109364/zip
2021-10-28T19:42:07-0400 [INFO    ] datalad_installer Running: 'C:\Users\DataLad\AppData\Local\Temp\tmpu3b6qkkl\git-annex-installer_8.20211028_x64.exe' /S
2021-10-28T19:42:07-0400 [INFO    ] datalad_installer Operation requires elevation; rerunning as administrator
2021-10-28T19:42:07-0400 [INFO    ] datalad_installer Running as administrator: C:\Users\DataLad\AppData\Local\Temp\tmpu3b6qkkl\git-annex-installer_8.20211028_x64.exe /S
Traceback (most recent call last):
  File "C:\Users\DataLad\miniconda3\envs\datalad-py3.9\lib\shutil.py", line 616, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\DataLad\\AppData\\Local\\Temp\\tmpu3b6qkkl\\git-annex-installer_8.20211028_x64.exe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\DataLad\miniconda3\envs\datalad-py3.9\lib\tempfile.py", line 801, in onerror
    _os.unlink(path)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\DataLad\\AppData\\Local\\Temp\\tmpu3b6qkkl\\git-annex-installer_8.20211028_x64.exe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\DataLad\miniconda3\envs\datalad-py3.9\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\DataLad\miniconda3\envs\datalad-py3.9\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\DataLad\miniconda3\envs\datalad-py3.9\Scripts\datalad-installer.exe\__main__.py", line 7, in <module>
  File "C:\Users\DataLad\miniconda3\envs\datalad-py3.9\lib\site-packages\datalad_installer.py", line 2158, in main
    return manager.main(argv)
  File "C:\Users\DataLad\miniconda3\envs\datalad-py3.9\lib\site-packages\datalad_installer.py", line 682, in main
    self.addcomponent(name=cr.name, **cr.kwargs)
  File "C:\Users\DataLad\miniconda3\envs\datalad-py3.9\lib\site-packages\datalad_installer.py", line 731, in addcomponent
    component(self).provide(**kwargs)
  File "C:\Users\DataLad\miniconda3\envs\datalad-py3.9\lib\site-packages\datalad_installer.py", line 1121, in provide
    bins = self.get_installer(method).install(self.NAME, **kwargs)
  File "C:\Users\DataLad\miniconda3\envs\datalad-py3.9\lib\site-packages\datalad_installer.py", line 1207, in install
    bindir = self.install_package(package, **kwargs)
  File "C:\Users\DataLad\miniconda3\envs\datalad-py3.9\lib\site-packages\datalad_installer.py", line 1745, in install_package
    raise AssertionError(
  File "C:\Users\DataLad\miniconda3\envs\datalad-py3.9\lib\tempfile.py", line 826, in __exit__
    self.cleanup()
  File "C:\Users\DataLad\miniconda3\envs\datalad-py3.9\lib\tempfile.py", line 830, in cleanup
    self._rmtree(self.name)
  File "C:\Users\DataLad\miniconda3\envs\datalad-py3.9\lib\tempfile.py", line 812, in _rmtree
    _shutil.rmtree(name, onerror=onerror)
  File "C:\Users\DataLad\miniconda3\envs\datalad-py3.9\lib\shutil.py", line 740, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\DataLad\miniconda3\envs\datalad-py3.9\lib\shutil.py", line 618, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Users\DataLad\miniconda3\envs\datalad-py3.9\lib\tempfile.py", line 804, in onerror
    cls._rmtree(path)
  File "C:\Users\DataLad\miniconda3\envs\datalad-py3.9\lib\tempfile.py", line 812, in _rmtree
    _shutil.rmtree(name, onerror=onerror)
  File "C:\Users\DataLad\miniconda3\envs\datalad-py3.9\lib\shutil.py", line 740, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\DataLad\miniconda3\envs\datalad-py3.9\lib\shutil.py", line 599, in _rmtree_unsafe
    onerror(os.scandir, path, sys.exc_info())
  File "C:\Users\DataLad\miniconda3\envs\datalad-py3.9\lib\shutil.py", line 596, in _rmtree_unsafe
    with os.scandir(path) as scandir_it:
NotADirectoryError: [WinError 267] The directory name is invalid: 'C:\\Users\\DataLad\\AppData\\Local\\Temp\\tmpu3b6qkkl\\git-annex-installer_8.20211028_x64.exe'
```

**Comment by adswa** [comment]
I was about to file the same issue, just observed it, too.

**Comment by jwodder** [comment]
@yarikoptic The actual error is an inability to delete the git-annex installer when cleaning up the temporary directory.  I suspect the file is still in use somehow when trying to delete it, and Windows doesn't allow that.  My attempt to work around this by following [this answer](https://stackoverflow.com/a/37256114/744178) to check whether the file was still in use and sleeping until it was no longer didn't work.

**Comment by yarikoptic** [comment]
How long did you sleep?

**Comment by yarikoptic** [comment]
I guess it needs to be troubleshooted with some fancy windows tools or may be psutil and get_open_files we have https://github.com/datalad/datalad/blob/HEAD/datalad/utils.py#L497 would give information?  depending on what process holds it, might need a fix in git annex installer (didn't happen initially when this code was added/tested, right?) or somewhere else

**Comment by adswa** [comment]
Probably the wrong way to tackle this, but to just share an anecdote: Going into the directory that is reported as having an invalid name as the last error and executing the exe file inside installs git-annex successfully.

**Comment by adswa** [comment]
I have to correct my previous comment, it is correctly installed even with the error.

**Comment by yarikoptic** [comment]
@adswa sorry for possibly asking you to reiterate: do you mean that we can safely ignore that error on Windows and just proceed forward?

**Comment by yarikoptic** [comment]
So,
- that particular exception comes from tempfile and it seems to be benign (may we? remove that directory before tempfile does in its cleanup?)
- but looking at above line where we get there: `datalad_installer.py", line 1745, in install_package \n     raise AssertionError(` it looks like it is this block of code:

```
        with tempfile.TemporaryDirectory() as tmpdir_:
            tmpdir = Path(tmpdir_)
            if ON_LINUX:
                self.download("ubuntu", tmpdir)
                (debpath,) = tmpdir.glob("*.deb")
                binpath = install_deb(
                    debpath,
                    self.manager,
                    Path("usr", "bin"),
                    install_dir=install_dir,
                )
            elif ON_MACOS:
                self.download("macos", tmpdir)
                (dmgpath,) = tmpdir.glob("*.dmg")
                binpath = install_git_annex_dmg(dmgpath, self.manager)
            elif ON_WINDOWS:
                self.download("windows", tmpdir)
                (exepath,) = tmpdir.glob("*.exe")
                self.manager.run_maybe_elevated(exepath, "/S")
                binpath = Path("C:/Program Files", "Git", "usr", "bin")
                self.manager.addpath(binpath)
            else:
                raise AssertionError(
                    "Method should not be called on unsupported platforms"
                )
```
so -- how did it endup in `else:` ???
or am I mixing up smth?  (and it is probably this context manager block which needs try/except to catch that not interesting exception)

**Comment by jwodder** [comment]
@yarikoptic So what exactly do you want the code to do about this?

**Comment by yarikoptic** [comment]
I don't know since I cannot understand how we ended up in that `raise AssertionError` if there is `elif ON_WINDOWS` right above it.  Do you see how that could happen?

**Comment by jwodder** [comment]
@yarikoptic My best guess is that it's a flaw in Python's traceback mechanism, and that the code actually reached the `elif ON_WINDOWS:` block before exiting the `with`, at which point it hit the error.

**Comment by yarikoptic** [comment]
ok. then I guess let's just allow (swallow and proceed) that PermissionError on Windows whenever it would be coming from tempfile. I do not see how the latter condition to meet without getting away from context manager into more explicit tempfile usage, but may be you see how.
