### ISSUE TITLE
Overly dramatic appearance on windows on first contact 

### ISSUE THREAD

**Issue by mih** [datalad/datalad-installer#94]
I installed it and naively typed `datalad-installer`:

```
C:\Users\mih>datalad-installer
2021-12-18T14:55:30+0100 [INFO    ] datalad_installer Writing environment modifications to C:\Users\mih\AppData\Local\Temp\dl-env-exlo4d0e.sh
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\mih\AppData\Roaming\Python\Python39\Scripts\datalad-installer.exe\__main__.py", line 7, in <module>
  File "C:\Users\mih\AppData\Roaming\Python\Python39\site-packages\datalad_installer.py", line 2158, in main
    return manager.main(argv)
  File "C:\Users\mih\AppData\Roaming\Python\Python39\site-packages\datalad_installer.py", line 682, in main
    self.addcomponent(name=cr.name, **cr.kwargs)
  File "C:\Users\mih\AppData\Roaming\Python\Python39\site-packages\datalad_installer.py", line 731, in addcomponent
    component(self).provide(**kwargs)
  File "C:\Users\mih\AppData\Roaming\Python\Python39\site-packages\datalad_installer.py", line 1133, in provide
    raise RuntimeError(f"No viable installation method for {self.NAME}")
RuntimeError: No viable installation method for datalad
```

Maybe this could become a message without a traceback? Or even something informative, suggesting possible mitigations?

**Comment by yarikoptic** [comment]
@jwodder WDYT? indeed it sounds a bit melo-dramatic. Can't it become a sequence of installations which would mimic something (didn't test) like

```
datalad-installer git-annex -m datalad/packages miniconda datalad -m conda-forge
```
?

**Comment by jwodder** [comment]
@yarikoptic I think we should move away from a "default" operation when `datalad-installer` is invoked without arguments, as we'll never get something satisfying for all uses; running just `datalad-installer` should just show a usage/help message.

**Comment by yarikoptic** [comment]
may be... not yet convinced since I think it should be feasible to just run `datalad-installer datalad` on pristine freshly installed box and get result quite consistently.  But I wonder if overall this relates to https://github.com/datalad/datalad-installer/issues/46 since IIRC and following http://handbook.datalad.org/en/latest/intro/installation.html?highlight=installation we need standalone (not in conda) installation of `git` for `git-annex` to operate Ok.  But I could be wrong.
