### ISSUE TITLE
dpkg might ask for confirmation!

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-installer#95]
Spotted that some runs on datalad-extensions were red, looked into logs which showed for datalad-neuroimaging https://ci.appveyor.com/project/mih/datalad-neuroimaging/branch/master/job/whry9ihktegs8no6 :

```
Processing triggers for libc-bin (2.31-0ubuntu9.2) ...
[ -n "${INSTALL_GITANNEX}" ] && python datalad_installer.py ${INSTALL_GITANNEX}
2021-10-22T13:30:12+0000 [INFO    ] datalad_installer Writing environment modifications to /home/appveyor/DLTMP/dl-env-1ede5pd6.sh
2021-10-22T13:30:12+0000 [INFO    ] datalad_installer Installing git-annex via deb-url
2021-10-22T13:30:12+0000 [INFO    ] datalad_installer URL: http://snapshot.debian.org/archive/debian/20210906T204127Z/pool/main/g/git-annex/git-annex_8.20210903-1_amd64.deb
2021-10-22T13:30:12+0000 [INFO    ] datalad_installer Extra args: None
2021-10-22T13:30:12+0000 [INFO    ] datalad_installer Downloading http://snapshot.debian.org/archive/debian/20210906T204127Z/pool/main/g/git-annex/git-annex_8.20210903-1_amd64.deb
About to run the following command as an administrator:
    dpkg -i /home/appveyor/DLTMP/tmpc1lgsy5j/git-annex.deb
Proceed? [y/a/n] Traceback (most recent call last):
  File "datalad_installer.py", line 2168, in <module>
    sys.exit(main(sys.argv))
  File "datalad_installer.py", line 2164, in main
    return manager.main(argv)
  File "datalad_installer.py", line 682, in main
    self.addcomponent(name=cr.name, **cr.kwargs)
  File "datalad_installer.py", line 731, in addcomponent
    component(self).provide(**kwargs)
  File "datalad_installer.py", line 1121, in provide
    bins = self.get_installer(method).install(self.NAME, **kwargs)
  File "datalad_installer.py", line 1207, in install
    bindir = self.install_package(package, **kwargs)
  File "datalad_installer.py", line 1516, in install_package
    binpath = install_deb(
  File "datalad_installer.py", line 2085, in install_deb
    manager.sudo(*cmd)
  File "datalad_installer.py", line 586, in sudo
    yan = ask("Proceed?", ["y", "a", "n"])
  File "datalad_installer.py", line 2106, in ask
    answer = input(full_prompt)
EOFError: EOF when reading a line
Command exited with code 1
Running "on_finish" scripts
while [ -f ~/BLOCK ]; do sleep 5; done
```

edits:
- that is on ubuntu focal 20.04
- I never saw such an interface change to `dpkg`.  might be ubuntu or appveyor ubuntu images specific?

**Comment by yarikoptic** [comment]
oh, nevermind -- it is not datalad installer issue, but how we invoke it needing to ok invocation of admin level operation.
